[#workshop_intro]
== Introduction

=== Workshop scenario

[IMPORTANT]
====
The workshop described in this paragraph is part of a larger workshop around application modernization and cloud-adoption. The complete workshop can be found link:https://github.com/redhat-mw-demos/app-mod-labs[here].
The narrative of the workshop evolves around a fictitious company, Globex, which recently embarked on a cloud adoption and application modernization journey for their flagship retail e-commerce application.
The described in the following chapters start when the first phase of this modernization journey has been successfully delivered.
====

The retail application has been modernized and refactored for running on the hybrid cloud. The original monolith application has been decomposed in a number of smaller microservices.

In Phase 2 of the modernization effort, the customer would like to enhance their modernized application to include new requirements and features.

* Track how visitors engage with their website, derive intelligence out of user activity streams.
* Process and analyze this user activity stream to showcase Featured Products based on products with the most customer interest leading to a more personalized experience.
* Introduce a multi-channel approach to build a mobile app as a new channel of access - mobile development is most likely to be outsourced

=== Common Challenges
There are however a number of challenges with the new requirements:

* Adding new channels remains difficult, with a high risk of tight coupling to the existing services, which would slow down development productivity and time to market.
* The existing services need to be managed and secured to allow access for external partners and development teams. Governance remains a challenge.
* Adoption of new technologies such as event streaming requires time and new skills, which are not readily available inside the company.

In order to cope with these challenges, the development team decides for a new approach.

=== Development approach
*Adoption of Apache Kafka* as a streaming platform to ingest and process user activity event streams.

*API First approach*:  the API contract is formalized in an OpenAPI spec document before development commences.  The API design phase is done collaboratively with all stakeholders. The first version of the OpenAPI spec document is pushed and managed in a schema registry, which acts as the system of truth. Mocks are created for the API.

*Parallel Development*: adopting an API first approach enables parallel development streams. 
- UI development teams and other API consumers start their development against the mocked APIs.  
- Backend development teams can implement the APIs using modern cloud-native frameworks and test the implementation against the OpenAPI spec to ensure that the implementation does not break the contract.

*Manage and Secure the APIs*: Adoption of an API management platform to expose the APIs in a secure and managed way for access by the mobile app and other 3rd party applications.

*Managed cloud services* as the preferred for easy and rapid adoption of new middleware components like the API Management platform and the streaming platform; this allows the teams to focus on the business requirements, without the need to invest in skills and infrastructure to deploy and maintain these complex components.

=== Workshop goals

The primary goal of the workshop is to guide the user through 

* Adding *Event Streaming capabilities* to an application to allow tracking user activity.
* Adding *API management capabilities* to an application to manage and secure the APIs for external access.

