= Enhancing Applications with Application Services
:sectnums:
:sectlinks:
:doctype: book

= Workshop

[#workshop_prerequisites]
== Prerequisites

To complete the workshop, the following is required from participants:

* Access to an OpenShift cluster on which the workshop components and applications have been deployed (see xref:04-workshop.adoc#workshop_provisioning[Provisioning])
+
[NOTE]
====
The workshop does not require a separate cluster for each participant, but can be delivered on a shared cluster where each participant has access to his own namespace with the workshop applications.   
====
* A Red Hat account to access the Developer Sandbox for OpenShift API Management and the Streams for Apache Kafka managed service.
+
A Red Hat account can be created by navigating to link:https://console.redhat.com[console.redhat.com] and following the *Register for a Red Hat account* link.
* (Optional) the `oc` OpenShift CLI installed on the participants workstation. The version of `oc` should match the version of the OpenShift cluster. +
The `oc` CLI can be obtained from the _command line tools_ page of the OpenShift cluster or from the link:https://access.redhat.com/downloads/content/290[OpenShift Container Platform downloads page] on the Red Hat Customer Portal.
* (Optional) the `rhoas` (Red Hat OpenShift Application Services) CLI installed on the participants workstation. +
The latest release of the `rhoas` CLI can be obtained from the link:https://github.com/redhat-developer/app-services-cli/releases/latest[Red Hat OpenShift Application Services CLI releases] page on GitHub.

[#workshop_provisioning]
== Provisioning the workshop environment

[IMPORTANT]
====
The provisioning instructions assume that each participant uses a separate OpenShift cluster. The provisioning Ansible workbook needs to be run for each OpenShift cluster.
Adapting the Ansible playbook for a shared OpenShift cluster is work in progress. 
====

* Clone the link:https://github.com/app-modernization-workshop-globex/ansible[Ansible playbook project] from Github to your local workstation.
* Copy the `inventories/inventory.template` file to `inventories/inventory`.
* Review the `inventories/inventory` file, and adapt where needed. In most cases, the file can be used as such. It assumes a trial version of OpenShift Streams for Apache Kafka will be used.
* Using `oc`, login as _cluster admin_ into the OpenShift cluster.
* Run the provisioning playbook
+
[.console-input]
[source,bash]
----
ansible-playbook -i inventories/inventory playbooks/install.yml
----
+
The playbook installs the following components:
* The Red Hat OpenShift Application Services (RHOAS) operator in the `openshift-operators` namespace.
* The Service Binding operator in the `openshift-operators` namespace.
* The Globex Coolstuff application in the `globex` namespace.

include::04-workshop-intro.adoc[]

include::04-workshop-streaming.adoc[]

include::04-workshop-api.adoc[]
